config/routes.rb
Rails.application.routes.draw do
  resources :albums
  resources :users, only: [:new, :create]
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  get 'welcome', to: 'sessions#welcome'
  get 'logout', to: 'sessions#destroy'

  root to: 'sessions#new'
end

app/models/album.rb
class Album < ApplicationRecord
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
    validates :username, uniqueness: true
    validates :full_name, :username, :password, :role, presence: true
    has_secure_password
    
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  before_action :set_album, only: %i[ show edit update destroy ]
  before_action :get_artists, only: %i[ new edit ]

  require 'rest-client'
  require 'json'

  # GET /albums or /albums.json
  def index
    @albums = Album.all
  end

  # GET /albums/1 or /albums/1.json
  def show
  end

  # GET /albums/new
  def new
    @album = Album.new
    @submit = 'Novo Album'
  end

  # GET /albums/1/edit
  def edit
    @submit = 'Editar Album'
  end

  # POST /albums or /albums.json
  def create
    @album = Album.new(album_params)

    respond_to do |format|
      if @album.save
        format.html { redirect_to @album, notice: "Album was successfully created." }
        format.json { render :show, status: :created, location: @album }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @album.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /albums/1 or /albums/1.json
  def update
    respond_to do |format|
      if @album.update(album_params)
        format.html { redirect_to @album, notice: "Album was successfully updated." }
        format.json { render :show, status: :ok, location: @album }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @album.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /albums/1 or /albums/1.json
  def destroy
    @album.destroy
    respond_to do |format|
      format.html { redirect_to albums_url, notice: "Album was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_album
      @album = Album.find(params[:id])
    end

    def get_artists
      @artists = []
      url = 'https://moat.ai/api/task'
      response = RestClient.get(url, headers={
        'Authorization': 'none',
        'Basic': 'ZGV2ZWxvcGVyOlpHVjJaV3h2Y0dWeQ=='
      })
      if response.code == 200
        names = JSON.parse(response.body)
        names.each do |n|
          @artists << n[0]['name']
        end
      else
        @artists = ['connection error, sorry']
      end
    end

    # Only allow a list of trusted parameters through.
    def album_params
      params.require(:album).permit(:artist, :album_name, :year)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    protect_from_forgery with: :exception
    
    before_action :authorize
    helper_method :current_user
    helper_method :logged_in?
    helper_method :is_admin?

    def current_user
       User.find_by(id: session[:user_id])
    end

    def logged_in?
           
        !current_user.nil?
    end    

    def is_admin?
        current_user && current_user.role == "admin" ? true : false
    end

    
    def authorize
        redirect_to '/login' unless logged_in?
    end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :authorize, only: [:new, :create, :welcome]

  def new
  end

  def create
    @user = User.find_by(username: params[:username])
    if logged_in?
      redirect_to '/albums'
    elsif @user && @user.authenticate(params[:password])
      session[:user_id] = @user.id
      redirect_to '/albums'
    else
       redirect_to '/login'
       flash[:alert] = "Sorry, we couldn't find an account with this username. Please check you're using the right username and try again."
    end
  end

  def login
  end

  def destroy
    session.delete(:user_id)
    @current_user = nil
    redirect_to root_url
  end
    
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :authorize, only: [:new, :create]

  def new
    @user = User.new
  end

  def create
    @user = User.create(params.require(:user).permit(:full_name, :username, :password, :role))

    session[:user_id] = @user.id

    redirect_to '/albums'
  end
end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/albums/_form.html.erb
<%= form_with(model: album, local: true) do |form| %>
  <% if album.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(album.errors.count, "error") %> prohibited this album from being saved:</h2>

      <ul>
        <% album.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="mb-3">
    <%= form.label :artist, class: 'form-label' %>
    <%= form.select(:artist, @artists, {}, {class: 'form-select'}) %>
  </div>

  <div class="mb-3">
    <%= form.label :album_name, class: 'form-label' %>
    <%= form.text_field :album_name, class: 'form-control' %>
  </div>

  <div class="mb-3">
    <%= form.label :year, class: 'form-label' %>
    <%= form.number_field :year, class: 'form-control' %>
  </div>

  <div class="actions">
    <%= form.submit @submit, class: "btn btn-primary" %>
  </div>
<% end %>
<br>

app/views/albums/edit.html.erb
<h1>Editing Album</h1>

<%= render 'form', album: @album %>

<%= link_to 'Show', @album %> |
<%= link_to 'Back', albums_path %>

app/views/albums/index.html.erb
<%= link_to "Log out", logout_path %>

<p id="notice"><%= notice %></p>

<h1>Albums</h1>

<table class="table">
  <thead>
    <tr>
      <th>Artist</th>
      <th>Album name</th>
      <th>Year</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @albums.each do |album| %>
      <tr>
        <td><%= album.artist %></td>
        <td><%= album.album_name %></td>
        <td><%= album.year %></td>
        <td><%= link_to 'Show', album %></td>
        <td><%= link_to 'Edit', edit_album_path(album) %></td>

        <% if is_admin? %>
          <td><%= link_to 'Destroy', album, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Album', new_album_path %>

app/views/albums/new.html.erb
<h1>New Album</h1>

<%= render 'form', album: @album %>

<%= link_to 'Back', albums_path %>

app/views/albums/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Artist:</strong>
  <%= @album.artist %>
</p>

<p>
  <strong>Album name:</strong>
  <%= @album.album_name %>
</p>

<p>
  <strong>Year:</strong>
  <%= @album.year %>
</p>

<%= link_to 'Edit', edit_album_path(@album) %> |
<%= link_to 'Back', albums_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MusicLibrary</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/users/new.html.erb
<h1>Sign Up</h1>

<%= form_for @user do |f|%>
    <div class="mb-3">   
        <%= f.label :full_name, class: 'form-label' %><br>
        <%= f.text_field :full_name, class: 'form-control' %><br>
    </div>
    <div class="mb-3">   
        <%= f.label :username, class: 'form-label' %><br>
        <%= f.text_field :username, class: 'form-control' %><br>
    </div>
    <div class="mb-3">   
        <%= f.label :password, class: 'form-label' %><br>
        <%= f.password_field :password, class: 'form-control' %><br>
    </div>
    <div class="mb-3">   
        <% if is_admin? %>
            <%= f.label :role, class: 'form-label' %><br>
            <%= f.select(:role, ["user", "admin"], {}, {class: 'form-select'}) %><br>
        <% else %>
            <%= f.hidden_field :role, value: "user" %><br>
        <% end %>
    </div>
  
  <%= f.submit "Sign up", class: "btn btn-primary" %>
<%end%>

<br>

<%= button_to "login", '/login', method: :get, class: "btn btn-dark" %>